micronaut:
  application:
    name: user_prefrences
  server:
    port: ${SERVER_PORT:8081}
datasources:
  default:
    url: jdbc:mysql://localhost:3306/user-prefrences-db
    username: root
    password: root
    schema-generated: CREATE-DROP
    dialect: MYSQL
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
netty:
  default:
    allocator:
      max-order: 3
